# Generated by Django 5.0.3 on 2024-03-23 06:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Logo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("logo_title", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "logo_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="desol/logo/image"
                    ),
                ),
                (
                    "logo_alt",
                    models.CharField(
                        blank=True, default="desol logo", max_length=50, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SocialMediaLinks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "social_title",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("social_link", models.URLField(blank=True, max_length=255, null=True)),
                (
                    "social_icon",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "social_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="desol/socials/<django.db.models.fields.CharField>/image",
                    ),
                ),
            ],
        ),
    ]
