# Generated by Django 5.0.3 on 2024-03-23 06:55

import desol_home.models.global_links
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("desol_home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Favicon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "favicon_title",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "favicon_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="desol/image/favicon"
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="socialmedialinks",
            name="social_icon",
        ),
        migrations.AddField(
            model_name="socialmedialinks",
            name="social_alt",
            field=models.CharField(
                blank=True,
                default="Desol Social Media Link",
                max_length=50,
                null=True,
                verbose_name="Social Alt Text",
            ),
        ),
        migrations.AlterField(
            model_name="logo",
            name="logo_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="desol/image/logo"
            ),
        ),
        migrations.AlterField(
            model_name="socialmedialinks",
            name="social_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=desol_home.models.global_links.SocialMediaLinks.upload_to_path,
            ),
        ),
    ]
