# Generated by Django 5.0.3 on 2024-03-23 07:05

import desol_home.models.global_links
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("desol_home", "0002_favicon_remove_socialmedialinks_social_icon_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="favicon",
            old_name="favicon_title",
            new_name="alt_text",
        ),
        migrations.RenameField(
            model_name="logo",
            old_name="logo_title",
            new_name="alt_text",
        ),
        migrations.RenameField(
            model_name="socialmedialinks",
            old_name="social_title",
            new_name="alt_text",
        ),
        migrations.RemoveField(
            model_name="favicon",
            name="favicon_image",
        ),
        migrations.RemoveField(
            model_name="logo",
            name="logo_alt",
        ),
        migrations.RemoveField(
            model_name="logo",
            name="logo_image",
        ),
        migrations.RemoveField(
            model_name="socialmedialinks",
            name="social_alt",
        ),
        migrations.RemoveField(
            model_name="socialmedialinks",
            name="social_image",
        ),
        migrations.RemoveField(
            model_name="socialmedialinks",
            name="social_link",
        ),
        migrations.AddField(
            model_name="favicon",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="desol/images/"),
        ),
        migrations.AddField(
            model_name="favicon",
            name="title",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="logo",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="desol/images/"),
        ),
        migrations.AddField(
            model_name="logo",
            name="title",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="socialmedialinks",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=desol_home.models.global_links.SocialMediaLinks.upload_to_path,
                verbose_name="Social Image",
            ),
        ),
        migrations.AddField(
            model_name="socialmedialinks",
            name="title",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
