# Generated by Django 5.0.3 on 2024-03-23 07:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("desol_home", "0003_rename_favicon_title_favicon_alt_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialmedialinks",
            name="link",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
