# Generated by Django 5.0.3 on 2024-03-23 08:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("desol_home", "0006_fourthfooter_mainfooter_secondfooter_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                ("reviews", models.TextField(blank=True, default="", null=True)),
            ],
        ),
    ]
