# Generated by Django 5.0.3 on 2024-03-29 04:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("desol_home", "0009_googlemapembed"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerreview",
            name="flag",
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
