# Generated by Django 5.0.3 on 2024-04-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("desol_home", "0013_delete_fourthfooter_delete_mainfooter_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomersDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=100, null=True)),
                ("last_name", models.CharField(blank=True, max_length=100, null=True)),
                ("email", models.EmailField(blank=True, max_length=100, null=True)),
                ("phone", models.PositiveIntegerField(blank=True, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                ("position", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "destination",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
