# Generated by Django 5.0.3 on 2024-04-08 12:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("desol_home", "0014_customersdetails"),
    ]

    operations = [
        migrations.AddField(
            model_name="customersdetails",
            name="customer_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
